# Generated by Django 5.1.3 on 2025-03-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
