# Generated by Django 5.1.3 on 2025-03-17 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Vandalism', 'Vandalism'), ('Fraud', 'Fraud'), ('Domestic Violence', 'Domestic Violence'), ('Cybercrime', 'Cybercrime'), ('Other', 'Other')], max_length=50)),
                ('incident_datetime', models.DateTimeField()),
                ('incident_description', models.TextField()),
                ('location', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('none', 'No contact')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
