# Generated by Django 5.1.3 on 2025-03-17 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_crimereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimereport',
            old_name='full_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='crimereport',
            old_name='incident_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='incident_datetime',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('none', 'No Contact')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
