# Generated by Django 5.1.3 on 2025-03-17 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_evidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimereport',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='crimereport',
            old_name='created_at',
            new_name='incident_datetime',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='preferred_contact',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='crimereport',
            name='address_details',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('none', 'No contact needed')], default='Unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
