# Generated by Django 5.1.3 on 2025-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0007_rename_email_crimereport_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
