# Generated by Django 5.1.3 on 2025-03-17 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0008_crimereport_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Vandalism', 'Vandalism'), ('Fraud', 'Fraud'), ('Domestic Violence', 'Domestic Violence'), ('Cybercrime', 'Cybercrime'), ('Other', 'Other')], max_length=50)),
                ('incident_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('address_details', models.TextField(default='Unknown')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
            ],
        ),
        migrations.RemoveField(
            model_name='crimereport',
            name='is_anonymous',
        ),
    ]
