# Generated by Django 5.1.3 on 2025-03-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0009_anonymouscrimereport_remove_crimereport_is_anonymous'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousCrimeReport',
        ),
    ]
