# Generated by Django 5.1.3 on 2025-03-20 14:50

from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_unique_tracking_number(apps, schema_editor):
    CrimeReport = apps.get_model('citizens', 'CrimeReport')
    for report in CrimeReport.objects.all():
        report.tracking_number = get_random_string(10).upper()
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0010_delete_anonymouscrimereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='', max_length=20, unique=False),
        ),
        migrations.RunPython(generate_unique_tracking_number),
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]