# Generated by Django 5.1.3 on 2025-03-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0011_crimereport_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
