# Generated by Django 5.1.3 on 2025-03-20 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0012_alter_crimereport_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='address_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='crime_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='incident_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
