# Generated by Django 5.1.3 on 2025-03-21 04:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0013_crimereport_status_alter_crimereport_address_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='status',
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='address_details',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='crime_type',
            field=models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Vandalism', 'Vandalism'), ('Fraud', 'Fraud'), ('Domestic Violence', 'Domestic Violence'), ('Cybercrime', 'Cybercrime'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='incident_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('none', 'No contact needed')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='51b547e8b2', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
