# Generated by Django 5.1.3 on 2025-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0014_remove_crimereport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='fbb667eae3', editable=False, max_length=20, unique=True),
        ),
    ]
