# Generated by Django 5.1.7 on 2025-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0018_customuser_citizen_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crimereport",
            name="tracking_number",
            field=models.CharField(
                default="fbce7f5aaa", editable=False, max_length=20, unique=True
            ),
        ),
    ]
