# Generated by Django 5.1.7 on 2025-03-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0021_alter_crimereport_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crimereport",
            name="tracking_number",
            field=models.CharField(
                default="e0e5ec1f9e", editable=False, max_length=20, unique=True
            ),
        ),
    ]
