# Generated by Django 5.1.7 on 2025-03-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0024_alter_crimereport_tracking_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crimereport",
            name="address_details",
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="tracking_number",
            field=models.CharField(
                default="bc8f812dbe", editable=False, max_length=20, unique=True
            ),
        ),
    ]
