# Generated by Django 5.1.7 on 2025-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0025_remove_crimereport_address_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crimereport",
            name="tracking_number",
            field=models.CharField(
                default="a0d36c71c4", editable=False, max_length=20, unique=True
            ),
        ),
    ]
