# Generated by Django 5.1.7 on 2025-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0026_alter_crimereport_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crimereport",
            name="evidence",
            field=models.FileField(
                blank=True, max_length=255, null=True, upload_to="evidence/"
            ),
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="preferred_contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("none", "No contact needed"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="tracking_number",
            field=models.CharField(
                default="d95a468ad7", editable=False, max_length=20, unique=True
            ),
        ),
    ]
