# Generated by Django 5.1.3 on 2025-03-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0029_alter_crimereport_tracking_number_policeuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policeuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='policeuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='policeuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='policeuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='d7a629932d', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='department',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policeuser',
            name='rank',
            field=models.CharField(default='Officer', max_length=50),
        ),
    ]
