# Generated by Django 5.1.3 on 2025-03-30 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0030_alter_policeuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='6ecd4b3f2e', editable=False, max_length=20, unique=True),
        ),
    ]
