# Generated by Django 5.1.3 on 2025-03-30 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0031_policeuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='policeuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='policeuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='35a26068e2', editable=False, max_length=20, unique=True),
        ),
    ]
