# Generated by Django 5.1.3 on 2025-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0033_alter_crimereport_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='policeuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='policeuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='policeuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='policeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='2be9aef2c0', editable=False, max_length=20, unique=True),
        ),
    ]
