# Generated by Django 5.1.3 on 2025-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0034_remove_policeuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='tracking_number',
            field=models.CharField(default='cb62e89a5d', editable=False, max_length=20, unique=True),
        ),
    ]
