# Generated by Django 5.1.7 on 2025-03-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0036_remove_policeuser_user_policeuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policeuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="policeuser",
            name="specialization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="tracking_number",
            field=models.CharField(
                default="1fedd03ffc", editable=False, max_length=20, unique=True
            ),
        ),
    ]
