# Generated by Django 5.1.7 on 2025-03-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0037_policeuser_phone_number_policeuser_specialization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crimereport",
            name="tracking_number",
            field=models.CharField(
                default="9092e871b8", editable=False, max_length=20, unique=True
            ),
        ),
    ]
