# Generated by Django 5.1.7 on 2025-03-31 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citizens", "0039_alter_crimereport_tracking_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimereport",
            name="assigned_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_cases",
                to="citizens.policeuser",
            ),
        ),
        migrations.AlterField(
            model_name="crimereport",
            name="tracking_number",
            field=models.CharField(
                default="79e03c43a1", editable=False, max_length=20, unique=True
            ),
        ),
    ]
